//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19 {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Covid19.AppResources.en", typeof(AppResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Afghanistan {
            get {
                return ResourceManager.GetString("Afghanistan", resourceCulture);
            }
        }
        
        internal static string Albania {
            get {
                return ResourceManager.GetString("Albania", resourceCulture);
            }
        }
        
        internal static string Algeria {
            get {
                return ResourceManager.GetString("Algeria", resourceCulture);
            }
        }
        
        internal static string Andorra {
            get {
                return ResourceManager.GetString("Andorra", resourceCulture);
            }
        }
        
        internal static string Angola {
            get {
                return ResourceManager.GetString("Angola", resourceCulture);
            }
        }
        
        internal static string Anguilla {
            get {
                return ResourceManager.GetString("Anguilla", resourceCulture);
            }
        }
        
        internal static string Antigua_and_Barbuda {
            get {
                return ResourceManager.GetString("Antigua and Barbuda", resourceCulture);
            }
        }
        
        internal static string Argentina {
            get {
                return ResourceManager.GetString("Argentina", resourceCulture);
            }
        }
        
        internal static string Armenia {
            get {
                return ResourceManager.GetString("Armenia", resourceCulture);
            }
        }
        
        internal static string Aruba {
            get {
                return ResourceManager.GetString("Aruba", resourceCulture);
            }
        }
        
        internal static string Australia {
            get {
                return ResourceManager.GetString("Australia", resourceCulture);
            }
        }
        
        internal static string Austria {
            get {
                return ResourceManager.GetString("Austria", resourceCulture);
            }
        }
        
        internal static string Azerbaijan {
            get {
                return ResourceManager.GetString("Azerbaijan", resourceCulture);
            }
        }
        
        internal static string Bahamas {
            get {
                return ResourceManager.GetString("Bahamas", resourceCulture);
            }
        }
        
        internal static string Bahrain {
            get {
                return ResourceManager.GetString("Bahrain", resourceCulture);
            }
        }
        
        internal static string Bangladesh {
            get {
                return ResourceManager.GetString("Bangladesh", resourceCulture);
            }
        }
        
        internal static string Barbados {
            get {
                return ResourceManager.GetString("Barbados", resourceCulture);
            }
        }
        
        internal static string Belarus {
            get {
                return ResourceManager.GetString("Belarus", resourceCulture);
            }
        }
        
        internal static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        internal static string Belize {
            get {
                return ResourceManager.GetString("Belize", resourceCulture);
            }
        }
        
        internal static string Benin {
            get {
                return ResourceManager.GetString("Benin", resourceCulture);
            }
        }
        
        internal static string Bermuda {
            get {
                return ResourceManager.GetString("Bermuda", resourceCulture);
            }
        }
        
        internal static string Bhutan {
            get {
                return ResourceManager.GetString("Bhutan", resourceCulture);
            }
        }
        
        internal static string Bolivia {
            get {
                return ResourceManager.GetString("Bolivia", resourceCulture);
            }
        }
        
        internal static string Bosnia {
            get {
                return ResourceManager.GetString("Bosnia", resourceCulture);
            }
        }
        
        internal static string Botswana {
            get {
                return ResourceManager.GetString("Botswana", resourceCulture);
            }
        }
        
        internal static string Brazil {
            get {
                return ResourceManager.GetString("Brazil", resourceCulture);
            }
        }
        
        internal static string British_Virgin_Islands {
            get {
                return ResourceManager.GetString("British Virgin Islands", resourceCulture);
            }
        }
        
        internal static string Brunei {
            get {
                return ResourceManager.GetString("Brunei", resourceCulture);
            }
        }
        
        internal static string Bulgaria {
            get {
                return ResourceManager.GetString("Bulgaria", resourceCulture);
            }
        }
        
        internal static string Burkina_Faso {
            get {
                return ResourceManager.GetString("Burkina Faso", resourceCulture);
            }
        }
        
        internal static string Burundi {
            get {
                return ResourceManager.GetString("Burundi", resourceCulture);
            }
        }
        
        internal static string Cabo_Verde {
            get {
                return ResourceManager.GetString("Cabo Verde", resourceCulture);
            }
        }
        
        internal static string Cambodia {
            get {
                return ResourceManager.GetString("Cambodia", resourceCulture);
            }
        }
        
        internal static string Cameroon {
            get {
                return ResourceManager.GetString("Cameroon", resourceCulture);
            }
        }
        
        internal static string Canada {
            get {
                return ResourceManager.GetString("Canada", resourceCulture);
            }
        }
        
        internal static string Caribbean_Netherlands {
            get {
                return ResourceManager.GetString("Caribbean Netherlands", resourceCulture);
            }
        }
        
        internal static string Cayman_Islands {
            get {
                return ResourceManager.GetString("Cayman Islands", resourceCulture);
            }
        }
        
        internal static string Central_African_Republic {
            get {
                return ResourceManager.GetString("Central African Republic", resourceCulture);
            }
        }
        
        internal static string Chad {
            get {
                return ResourceManager.GetString("Chad", resourceCulture);
            }
        }
        
        internal static string Channel_Islands {
            get {
                return ResourceManager.GetString("Channel Islands", resourceCulture);
            }
        }
        
        internal static string Chile {
            get {
                return ResourceManager.GetString("Chile", resourceCulture);
            }
        }
        
        internal static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        internal static string Colombia {
            get {
                return ResourceManager.GetString("Colombia", resourceCulture);
            }
        }
        
        internal static string ConfirmedHeader {
            get {
                return ResourceManager.GetString("ConfirmedHeader", resourceCulture);
            }
        }
        
        internal static string Congo {
            get {
                return ResourceManager.GetString("Congo", resourceCulture);
            }
        }
        
        internal static string Costa_Rica {
            get {
                return ResourceManager.GetString("Costa Rica", resourceCulture);
            }
        }
        
        internal static string CountriesFacing {
            get {
                return ResourceManager.GetString("CountriesFacing", resourceCulture);
            }
        }
        
        internal static string CountrySubtitle {
            get {
                return ResourceManager.GetString("CountrySubtitle", resourceCulture);
            }
        }
        
        internal static string Croatia {
            get {
                return ResourceManager.GetString("Croatia", resourceCulture);
            }
        }
        
        internal static string Cuba {
            get {
                return ResourceManager.GetString("Cuba", resourceCulture);
            }
        }
        
        internal static string Curaçao {
            get {
                return ResourceManager.GetString("Curaçao", resourceCulture);
            }
        }
        
        internal static string Cyprus {
            get {
                return ResourceManager.GetString("Cyprus", resourceCulture);
            }
        }
        
        internal static string Czechia {
            get {
                return ResourceManager.GetString("Czechia", resourceCulture);
            }
        }
        
        internal static string Côte_d_Ivoire {
            get {
                return ResourceManager.GetString("Côte d\'Ivoire", resourceCulture);
            }
        }
        
        internal static string DeathsHeader {
            get {
                return ResourceManager.GetString("DeathsHeader", resourceCulture);
            }
        }
        
        internal static string Denmark {
            get {
                return ResourceManager.GetString("Denmark", resourceCulture);
            }
        }
        
        internal static string Diamond_Princess {
            get {
                return ResourceManager.GetString("Diamond Princess", resourceCulture);
            }
        }
        
        internal static string Djibouti {
            get {
                return ResourceManager.GetString("Djibouti", resourceCulture);
            }
        }
        
        internal static string Dominica {
            get {
                return ResourceManager.GetString("Dominica", resourceCulture);
            }
        }
        
        internal static string Dominican_Republic {
            get {
                return ResourceManager.GetString("Dominican Republic", resourceCulture);
            }
        }
        
        internal static string DRC {
            get {
                return ResourceManager.GetString("DRC", resourceCulture);
            }
        }
        
        internal static string Ecuador {
            get {
                return ResourceManager.GetString("Ecuador", resourceCulture);
            }
        }
        
        internal static string Egypt {
            get {
                return ResourceManager.GetString("Egypt", resourceCulture);
            }
        }
        
        internal static string El_Salvador {
            get {
                return ResourceManager.GetString("El Salvador", resourceCulture);
            }
        }
        
        internal static string Equatorial_Guinea {
            get {
                return ResourceManager.GetString("Equatorial Guinea", resourceCulture);
            }
        }
        
        internal static string Eritrea {
            get {
                return ResourceManager.GetString("Eritrea", resourceCulture);
            }
        }
        
        internal static string Estonia {
            get {
                return ResourceManager.GetString("Estonia", resourceCulture);
            }
        }
        
        internal static string Ethiopia {
            get {
                return ResourceManager.GetString("Ethiopia", resourceCulture);
            }
        }
        
        internal static string Falkland_Islands__Malvinas_ {
            get {
                return ResourceManager.GetString("Falkland Islands (Malvinas)", resourceCulture);
            }
        }
        
        internal static string Faroe_Islands {
            get {
                return ResourceManager.GetString("Faroe Islands", resourceCulture);
            }
        }
        
        internal static string Fiji {
            get {
                return ResourceManager.GetString("Fiji", resourceCulture);
            }
        }
        
        internal static string Finland {
            get {
                return ResourceManager.GetString("Finland", resourceCulture);
            }
        }
        
        internal static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        internal static string French_Guiana {
            get {
                return ResourceManager.GetString("French Guiana", resourceCulture);
            }
        }
        
        internal static string French_Polynesia {
            get {
                return ResourceManager.GetString("French Polynesia", resourceCulture);
            }
        }
        
        internal static string Gabon {
            get {
                return ResourceManager.GetString("Gabon", resourceCulture);
            }
        }
        
        internal static string Gambia {
            get {
                return ResourceManager.GetString("Gambia", resourceCulture);
            }
        }
        
        internal static string Georgia {
            get {
                return ResourceManager.GetString("Georgia", resourceCulture);
            }
        }
        
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        internal static string Ghana {
            get {
                return ResourceManager.GetString("Ghana", resourceCulture);
            }
        }
        
        internal static string Gibraltar {
            get {
                return ResourceManager.GetString("Gibraltar", resourceCulture);
            }
        }
        
        internal static string GlobalUpdateHeader {
            get {
                return ResourceManager.GetString("GlobalUpdateHeader", resourceCulture);
            }
        }
        
        internal static string Greece {
            get {
                return ResourceManager.GetString("Greece", resourceCulture);
            }
        }
        
        internal static string Greenland {
            get {
                return ResourceManager.GetString("Greenland", resourceCulture);
            }
        }
        
        internal static string Grenada {
            get {
                return ResourceManager.GetString("Grenada", resourceCulture);
            }
        }
        
        internal static string Guadeloupe {
            get {
                return ResourceManager.GetString("Guadeloupe", resourceCulture);
            }
        }
        
        internal static string Guatemala {
            get {
                return ResourceManager.GetString("Guatemala", resourceCulture);
            }
        }
        
        internal static string Guinea {
            get {
                return ResourceManager.GetString("Guinea", resourceCulture);
            }
        }
        
        internal static string Guinea_Bissau {
            get {
                return ResourceManager.GetString("Guinea-Bissau", resourceCulture);
            }
        }
        
        internal static string Guyana {
            get {
                return ResourceManager.GetString("Guyana", resourceCulture);
            }
        }
        
        internal static string Haiti {
            get {
                return ResourceManager.GetString("Haiti", resourceCulture);
            }
        }
        
        internal static string HashTagCovid {
            get {
                return ResourceManager.GetString("HashTagCovid", resourceCulture);
            }
        }
        
        internal static string Holy_See__Vatican_City_State_ {
            get {
                return ResourceManager.GetString("Holy See (Vatican City State)", resourceCulture);
            }
        }
        
        internal static string Honduras {
            get {
                return ResourceManager.GetString("Honduras", resourceCulture);
            }
        }
        
        internal static string Hong_Kong {
            get {
                return ResourceManager.GetString("Hong Kong", resourceCulture);
            }
        }
        
        internal static string Hungary {
            get {
                return ResourceManager.GetString("Hungary", resourceCulture);
            }
        }
        
        internal static string Iceland {
            get {
                return ResourceManager.GetString("Iceland", resourceCulture);
            }
        }
        
        internal static string India {
            get {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }
        
        internal static string Indonesia {
            get {
                return ResourceManager.GetString("Indonesia", resourceCulture);
            }
        }
        
        internal static string InternetMessageOffLine {
            get {
                return ResourceManager.GetString("InternetMessageOffLine", resourceCulture);
            }
        }
        
        internal static string InternetNotConnected {
            get {
                return ResourceManager.GetString("InternetNotConnected", resourceCulture);
            }
        }
        
        internal static string Iran {
            get {
                return ResourceManager.GetString("Iran", resourceCulture);
            }
        }
        
        internal static string Iraq {
            get {
                return ResourceManager.GetString("Iraq", resourceCulture);
            }
        }
        
        internal static string Ireland {
            get {
                return ResourceManager.GetString("Ireland", resourceCulture);
            }
        }
        
        internal static string Isle_of_Man {
            get {
                return ResourceManager.GetString("Isle of Man", resourceCulture);
            }
        }
        
        internal static string Israel {
            get {
                return ResourceManager.GetString("Israel", resourceCulture);
            }
        }
        
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        internal static string Jamaica {
            get {
                return ResourceManager.GetString("Jamaica", resourceCulture);
            }
        }
        
        internal static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        internal static string Jordan {
            get {
                return ResourceManager.GetString("Jordan", resourceCulture);
            }
        }
        
        internal static string Kazakhstan {
            get {
                return ResourceManager.GetString("Kazakhstan", resourceCulture);
            }
        }
        
        internal static string Kenya {
            get {
                return ResourceManager.GetString("Kenya", resourceCulture);
            }
        }
        
        internal static string Kuwait {
            get {
                return ResourceManager.GetString("Kuwait", resourceCulture);
            }
        }
        
        internal static string Kyrgyzstan {
            get {
                return ResourceManager.GetString("Kyrgyzstan", resourceCulture);
            }
        }
        
        internal static string Lao_People_s_Democratic_Republic {
            get {
                return ResourceManager.GetString("Lao People\'s Democratic Republic", resourceCulture);
            }
        }
        
        internal static string Latvia {
            get {
                return ResourceManager.GetString("Latvia", resourceCulture);
            }
        }
        
        internal static string LearnAboutCovid {
            get {
                return ResourceManager.GetString("LearnAboutCovid", resourceCulture);
            }
        }
        
        internal static string Lebanon {
            get {
                return ResourceManager.GetString("Lebanon", resourceCulture);
            }
        }
        
        internal static string Liberia {
            get {
                return ResourceManager.GetString("Liberia", resourceCulture);
            }
        }
        
        internal static string Libyan_Arab_Jamahiriya {
            get {
                return ResourceManager.GetString("Libyan Arab Jamahiriya", resourceCulture);
            }
        }
        
        internal static string Liechtenstein {
            get {
                return ResourceManager.GetString("Liechtenstein", resourceCulture);
            }
        }
        
        internal static string Lithuania {
            get {
                return ResourceManager.GetString("Lithuania", resourceCulture);
            }
        }
        
        internal static string Luxembourg {
            get {
                return ResourceManager.GetString("Luxembourg", resourceCulture);
            }
        }
        
        internal static string Macao {
            get {
                return ResourceManager.GetString("Macao", resourceCulture);
            }
        }
        
        internal static string Macedonia {
            get {
                return ResourceManager.GetString("Macedonia", resourceCulture);
            }
        }
        
        internal static string Madagascar {
            get {
                return ResourceManager.GetString("Madagascar", resourceCulture);
            }
        }
        
        internal static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        internal static string MainHeaderSubtitle {
            get {
                return ResourceManager.GetString("MainHeaderSubtitle", resourceCulture);
            }
        }
        
        internal static string Malawi {
            get {
                return ResourceManager.GetString("Malawi", resourceCulture);
            }
        }
        
        internal static string Malaysia {
            get {
                return ResourceManager.GetString("Malaysia", resourceCulture);
            }
        }
        
        internal static string Maldives {
            get {
                return ResourceManager.GetString("Maldives", resourceCulture);
            }
        }
        
        internal static string Mali {
            get {
                return ResourceManager.GetString("Mali", resourceCulture);
            }
        }
        
        internal static string Malta {
            get {
                return ResourceManager.GetString("Malta", resourceCulture);
            }
        }
        
        internal static string Martinique {
            get {
                return ResourceManager.GetString("Martinique", resourceCulture);
            }
        }
        
        internal static string Mauritania {
            get {
                return ResourceManager.GetString("Mauritania", resourceCulture);
            }
        }
        
        internal static string Mauritius {
            get {
                return ResourceManager.GetString("Mauritius", resourceCulture);
            }
        }
        
        internal static string Mayotte {
            get {
                return ResourceManager.GetString("Mayotte", resourceCulture);
            }
        }
        
        internal static string MessageLoader {
            get {
                return ResourceManager.GetString("MessageLoader", resourceCulture);
            }
        }
        
        internal static string Mexico {
            get {
                return ResourceManager.GetString("Mexico", resourceCulture);
            }
        }
        
        internal static string Moldova {
            get {
                return ResourceManager.GetString("Moldova", resourceCulture);
            }
        }
        
        internal static string Monaco {
            get {
                return ResourceManager.GetString("Monaco", resourceCulture);
            }
        }
        
        internal static string Mongolia {
            get {
                return ResourceManager.GetString("Mongolia", resourceCulture);
            }
        }
        
        internal static string Montenegro {
            get {
                return ResourceManager.GetString("Montenegro", resourceCulture);
            }
        }
        
        internal static string Montserrat {
            get {
                return ResourceManager.GetString("Montserrat", resourceCulture);
            }
        }
        
        internal static string Morocco {
            get {
                return ResourceManager.GetString("Morocco", resourceCulture);
            }
        }
        
        internal static string Mozambique {
            get {
                return ResourceManager.GetString("Mozambique", resourceCulture);
            }
        }
        
        internal static string MS_Zaandam {
            get {
                return ResourceManager.GetString("MS Zaandam", resourceCulture);
            }
        }
        
        internal static string Myanmar {
            get {
                return ResourceManager.GetString("Myanmar", resourceCulture);
            }
        }
        
        internal static string Namibia {
            get {
                return ResourceManager.GetString("Namibia", resourceCulture);
            }
        }
        
        internal static string Nepal {
            get {
                return ResourceManager.GetString("Nepal", resourceCulture);
            }
        }
        
        internal static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        internal static string New_Caledonia {
            get {
                return ResourceManager.GetString("New Caledonia", resourceCulture);
            }
        }
        
        internal static string New_Zealand {
            get {
                return ResourceManager.GetString("New Zealand", resourceCulture);
            }
        }
        
        internal static string Nicaragua {
            get {
                return ResourceManager.GetString("Nicaragua", resourceCulture);
            }
        }
        
        internal static string Niger {
            get {
                return ResourceManager.GetString("Niger", resourceCulture);
            }
        }
        
        internal static string Nigeria {
            get {
                return ResourceManager.GetString("Nigeria", resourceCulture);
            }
        }
        
        internal static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        internal static string Oman {
            get {
                return ResourceManager.GetString("Oman", resourceCulture);
            }
        }
        
        internal static string Pakistan {
            get {
                return ResourceManager.GetString("Pakistan", resourceCulture);
            }
        }
        
        internal static string Palestine {
            get {
                return ResourceManager.GetString("Palestine", resourceCulture);
            }
        }
        
        internal static string Panama {
            get {
                return ResourceManager.GetString("Panama", resourceCulture);
            }
        }
        
        internal static string Papua_New_Guinea {
            get {
                return ResourceManager.GetString("Papua New Guinea", resourceCulture);
            }
        }
        
        internal static string Paraguay {
            get {
                return ResourceManager.GetString("Paraguay", resourceCulture);
            }
        }
        
        internal static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        internal static string Philippines {
            get {
                return ResourceManager.GetString("Philippines", resourceCulture);
            }
        }
        
        internal static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        internal static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        internal static string Qatar {
            get {
                return ResourceManager.GetString("Qatar", resourceCulture);
            }
        }
        
        internal static string ReadMoreCovid {
            get {
                return ResourceManager.GetString("ReadMoreCovid", resourceCulture);
            }
        }
        
        internal static string RecoveredHeader {
            get {
                return ResourceManager.GetString("RecoveredHeader", resourceCulture);
            }
        }
        
        internal static string RefreshHeader {
            get {
                return ResourceManager.GetString("RefreshHeader", resourceCulture);
            }
        }
        
        internal static string Romania {
            get {
                return ResourceManager.GetString("Romania", resourceCulture);
            }
        }
        
        internal static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        internal static string Rwanda {
            get {
                return ResourceManager.GetString("Rwanda", resourceCulture);
            }
        }
        
        internal static string Réunion {
            get {
                return ResourceManager.GetString("Réunion", resourceCulture);
            }
        }
        
        internal static string S__Korea {
            get {
                return ResourceManager.GetString("S. Korea", resourceCulture);
            }
        }
        
        internal static string Saint_Kitts_and_Nevis {
            get {
                return ResourceManager.GetString("Saint Kitts and Nevis", resourceCulture);
            }
        }
        
        internal static string Saint_Lucia {
            get {
                return ResourceManager.GetString("Saint Lucia", resourceCulture);
            }
        }
        
        internal static string Saint_Martin {
            get {
                return ResourceManager.GetString("Saint Martin", resourceCulture);
            }
        }
        
        internal static string Saint_Pierre_Miquelon {
            get {
                return ResourceManager.GetString("Saint Pierre Miquelon", resourceCulture);
            }
        }
        
        internal static string Saint_Vincent_and_the_Grenadines {
            get {
                return ResourceManager.GetString("Saint Vincent and the Grenadines", resourceCulture);
            }
        }
        
        internal static string San_Marino {
            get {
                return ResourceManager.GetString("San Marino", resourceCulture);
            }
        }
        
        internal static string Sao_Tome_and_Principe {
            get {
                return ResourceManager.GetString("Sao Tome and Principe", resourceCulture);
            }
        }
        
        internal static string Saudi_Arabia {
            get {
                return ResourceManager.GetString("Saudi Arabia", resourceCulture);
            }
        }
        
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        internal static string SelectionLanguage {
            get {
                return ResourceManager.GetString("SelectionLanguage", resourceCulture);
            }
        }
        
        internal static string SelectOneCountryList {
            get {
                return ResourceManager.GetString("SelectOneCountryList", resourceCulture);
            }
        }
        
        internal static string Senegal {
            get {
                return ResourceManager.GetString("Senegal", resourceCulture);
            }
        }
        
        internal static string Serbia {
            get {
                return ResourceManager.GetString("Serbia", resourceCulture);
            }
        }
        
        internal static string Seychelles {
            get {
                return ResourceManager.GetString("Seychelles", resourceCulture);
            }
        }
        
        internal static string Sierra_Leone {
            get {
                return ResourceManager.GetString("Sierra Leone", resourceCulture);
            }
        }
        
        internal static string Singapore {
            get {
                return ResourceManager.GetString("Singapore", resourceCulture);
            }
        }
        
        internal static string Sint_Maarten {
            get {
                return ResourceManager.GetString("Sint Maarten", resourceCulture);
            }
        }
        
        internal static string Slovakia {
            get {
                return ResourceManager.GetString("Slovakia", resourceCulture);
            }
        }
        
        internal static string Slovenia {
            get {
                return ResourceManager.GetString("Slovenia", resourceCulture);
            }
        }
        
        internal static string Somalia {
            get {
                return ResourceManager.GetString("Somalia", resourceCulture);
            }
        }
        
        internal static string South_Africa {
            get {
                return ResourceManager.GetString("South Africa", resourceCulture);
            }
        }
        
        internal static string South_Sudan {
            get {
                return ResourceManager.GetString("South Sudan", resourceCulture);
            }
        }
        
        internal static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        internal static string Sri_Lanka {
            get {
                return ResourceManager.GetString("Sri Lanka", resourceCulture);
            }
        }
        
        internal static string St__Barth {
            get {
                return ResourceManager.GetString("St. Barth", resourceCulture);
            }
        }
        
        internal static string Sudan {
            get {
                return ResourceManager.GetString("Sudan", resourceCulture);
            }
        }
        
        internal static string Suriname {
            get {
                return ResourceManager.GetString("Suriname", resourceCulture);
            }
        }
        
        internal static string Swaziland {
            get {
                return ResourceManager.GetString("Swaziland", resourceCulture);
            }
        }
        
        internal static string Sweden {
            get {
                return ResourceManager.GetString("Sweden", resourceCulture);
            }
        }
        
        internal static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        internal static string Syrian_Arab_Republic {
            get {
                return ResourceManager.GetString("Syrian Arab Republic", resourceCulture);
            }
        }
        
        internal static string Taiwan {
            get {
                return ResourceManager.GetString("Taiwan", resourceCulture);
            }
        }
        
        internal static string Tanzania {
            get {
                return ResourceManager.GetString("Tanzania", resourceCulture);
            }
        }
        
        internal static string Thailand {
            get {
                return ResourceManager.GetString("Thailand", resourceCulture);
            }
        }
        
        internal static string ThemeSelection {
            get {
                return ResourceManager.GetString("ThemeSelection", resourceCulture);
            }
        }
        
        internal static string Timor_Leste {
            get {
                return ResourceManager.GetString("Timor-Leste", resourceCulture);
            }
        }
        
        internal static string Togo {
            get {
                return ResourceManager.GetString("Togo", resourceCulture);
            }
        }
        
        internal static string Trinidad_and_Tobago {
            get {
                return ResourceManager.GetString("Trinidad and Tobago", resourceCulture);
            }
        }
        
        internal static string Tunisia {
            get {
                return ResourceManager.GetString("Tunisia", resourceCulture);
            }
        }
        
        internal static string Turkey {
            get {
                return ResourceManager.GetString("Turkey", resourceCulture);
            }
        }
        
        internal static string Turks_and_Caicos_Islands {
            get {
                return ResourceManager.GetString("Turks and Caicos Islands", resourceCulture);
            }
        }
        
        internal static string UAE {
            get {
                return ResourceManager.GetString("UAE", resourceCulture);
            }
        }
        
        internal static string Uganda {
            get {
                return ResourceManager.GetString("Uganda", resourceCulture);
            }
        }
        
        internal static string UK {
            get {
                return ResourceManager.GetString("UK", resourceCulture);
            }
        }
        
        internal static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        internal static string Uruguay {
            get {
                return ResourceManager.GetString("Uruguay", resourceCulture);
            }
        }
        
        internal static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
        
        internal static string Uzbekistan {
            get {
                return ResourceManager.GetString("Uzbekistan", resourceCulture);
            }
        }
        
        internal static string Venezuela {
            get {
                return ResourceManager.GetString("Venezuela", resourceCulture);
            }
        }
        
        internal static string Vietnam {
            get {
                return ResourceManager.GetString("Vietnam", resourceCulture);
            }
        }
        
        internal static string Western_Sahara {
            get {
                return ResourceManager.GetString("Western Sahara", resourceCulture);
            }
        }
        
        internal static string Yemen {
            get {
                return ResourceManager.GetString("Yemen", resourceCulture);
            }
        }
        
        internal static string Zambia {
            get {
                return ResourceManager.GetString("Zambia", resourceCulture);
            }
        }
        
        internal static string Zimbabwe {
            get {
                return ResourceManager.GetString("Zimbabwe", resourceCulture);
            }
        }
    }
}
